### ISSUE TITLE
Labeled Volcano Plot - vignette and parameters

### ISSUE THREAD

**Issue by rvitancol** [Nanostring-Biostats/DSPPlugins#23]
Add the following sections in the vignette
- [x] Loading into the DSP-DA - Rename Running the plugin section to Loading into the DSP-DA. Add the section on how to run plugins in DSP-DA at the beginning of this section. (Refer to Dim Reduction Plugin)
- [x] Setting User Parameters - be more specific, what values can the parameters take
- [x] Example Parameter Set-up - change the Interpretation of Results Section to Example Parameter Set-up
- [x] Interpretation of Results - maybe we can skip this for now. I will confirm with Prajan if he needs this for volcano plot.

- [x] R script - change the Target Name to Target name or better to make it case insensitive.

**Comment by maddygriz** [comment]
Vignette has been updated to look more like the Dim Reduction vignette.

**Comment by rvitancol** [comment]
closing this issue. Volcano plot is merged in master branch.
