### ISSUE TITLE
DimReduction supporting document updates

### ISSUE THREAD

**Issue by JasonWReeves** [Nanostring-Biostats/DSPPlugins#32]
- [x] changelog
- [x] vignette note about scaled data
- [x] function version number
- [x] update website to match vignette

**Comment by JasonWReeves** [comment]
@sgiske & @rvitancol - I've updated the vignette documents. Can you review these to confirm that the adjustments are sufficient?

The text updates are found on page 7 in the first paragraph of the PCA section.
If these are appropriate for use - please use this to update the text in the similar documentation on the website

**Comment by rvitancol** [comment]
@JasonWReeves , can you fetch master branch before making edits in the dim reduction vignette? This has been changed since the original commit. I cannot merge your changes, github does not allow me to combine non-text file.

**Comment by rvitancol** [comment]
@sgiske You can check what's changed in the vignette here since track changes is turned on (page7).
https://github.com/Nanostring-Biostats/DSPPlugins/blob/dim_reduction_plugin/DimReduction/dimension-reduction-vignette.docx

**Comment by sgiske** [comment]
> @sgiske You can check what's changed in the vignette here since track changes is turned on (page7).
> https://github.com/Nanostring-Biostats/DSPPlugins/blob/dim_reduction_plugin/DimReduction/dimension-reduction-vignette.docx

Thank you! I will check it out.

**Comment by rvitancol** [comment]
this is updated in website
