### ISSUE TITLE
SpatialDecon v1.1 ready for update to GeoScriptHub

### ISSUE THREAD

**Issue by rvitancol** [Nanostring-Biostats/DSPPlugins#39]
- [x] changelog
- [x] vignette update (bar plots in vignette need to be updated)
- [x] function version number
- [ ] update website to match vignette

**Comment by rvitancol** [comment]
@patrickjdanaher Do you remember which dataset you used for the vignette? Need to update the barplots in the vignette to reflect the change.

**Comment by sgiske** [comment]
Excellent! We will need to add Change log and version number to both the Vignette and Web to reflect the changes.

**Comment by rvitancol** [comment]
@sgiske Vignette is updated. 
@buffler Please update website. Thanks!

**Comment by sgiske** [comment]
Thank you

**Comment by rvitancol** [comment]
re-open as per @sgiske request. To be closed when website is updated.

**Comment by sgiske** [comment]
Updated! Thank you!
